<?php
function agb() {
	echo '
     AGBAnwendbarkeitDie Insertionsbedingungen regeln die vertraglichen Beziehungen zwischen dem Inserenten resp. dem von ihm beauftragten Werbevermittler und den Betreibern der Webseite, sofern nicht schriftlich etwas anderes vereinbart worden ist. Insoweit diese Bedingungen keine abweichenden Regeln enthalten, gelten für das Vertragsverhältnis die Vorschriften über den Werkvertrag (Art. 363 ff. OR). Insertionspreisefür Privatpersonen ist das Standard-Inserat bis auf weiteres gratis.InserateaufgabeDer Inserent bzw. der Werbevermittler geben das Inserat online auf."Gut zum Druck"Erfolgt durch Inserenten implizit mit der Online-Bestellung (abschicken, senden).
HaftungDer Inserent ist für den Inhalt der Online-Inserate verantwortlich. Er ist verpflichtet, die einschlägigen gesetzlichen Bestimmungen, Richtlinien und Verbandsregeln der Branche einzuhalten und stellt, so weit rechtlich möglich, den Betreiber der Webseite, dessen Organe und Hilfspersonen von jeglichen Ansprüchen Dritter frei. Wird der Betreiber der Webseite gerichtlich belangt, ist der Inserent verpflichtet, nach erfolgter Strafverkündigung dem Prozess beizutreten. Der Inserent ist in jedem Falle verpflichtet, sämtliche im Zusammenhang mit Ansprüchen Dritter anfallenden gerichtlichen und aussergerichtlichen Kosten zu übernehmen. DatenschutzDer Inserent bzw. der Werbevermittler erlaubt dem Betreiber der Webseite bis auf Widerruf, die Inserate auf Online-Dienste einzuspeisen oder sonstwie zu veröffentlichen und zu diesem Zweck zu bearbeiten. Der Betreiber der Webseite verpflichtet sich zur Einhaltung der datenschutzrechtlichen Bestimmungen, kann aber die Vertraulichkeit, Integrität, Authentizität und Verfügbarkeit von Personendaten nicht umfassend garantieren. Der Inserent bzw. der Werbevermittler nimmt zur Kenntnis, dass Personendaten auch in Staaten abrufbar sind, die keine der Schweiz vergleichbaren Datenschutzbestimmungen kennen. Der Inserent bzw. der Werbevermittler ist damit einverstanden, dass die Online- Inserate für Dritte nicht frei verfügbar sind. Der Inserent bzw. der Werbevermittler untersagt insbesondere die Uebernahme von Online-Inseraten auf Online-Dienste von Dritten und überträgt dem Betreiber der Webseite das Recht, jede irgendwie geartete Verwertung und Bearbeitung dieser Inserate mit den geeigneten Mitteln zu untersagen.ModerationDie Betreiber von wgzimmer.ch sind ermächtigt, Inserate ohne Angabe von Gründen zu löschen. Ebenfalls sind die Betreiber ermächtigt, einzelne Benutzer ohne Angabe von Gründen zu sperren. Werbung auf wgzimmer.chDie Platzierung von Werbung in Inseraten ist nicht erlaubt. Insbesondere betrifft dies Werbung für andere, kommerzielle und nichtkommerzielle Wohnungsanbieter. Ebenfalls ist die Platzierung von Werbung in Einträgen in Gästebuch oder Anekdoten untersagt.

Diese Inserationsbedingungen treten am 09.04.2006 in Kraft.

Die Betreiber der Webseite, Basel.';
}
?>
